#env CUDA_VISIBLE_DEVICES=0 SA_SPLIT=test python -m experiments.benchmark_with_steering --model qwen-2.5-14b-instruct --n 100 --examples 0 --tasks id_leverage --vector-variant plain --steering-mode add --vector-source id_leverage --coefficient 0.05 --layers 25 --out-dir experiments/results/qwen_steering --comment "vv=plain coef=0.025 layers=25"
env CUDA_VISIBLE_DEVICES=1 SA_SPLIT=test python -m experiments.benchmark_with_steering --model qwen-2.5-14b-instruct --n 100 --examples 0 --tasks id_leverage --vector-variant plain --steering-mode add --vector-source id_leverage --coefficient 0.05 --layers 25 --out-dir experiments/results/qwen_steering --comment "vv=plain coef=0.05 layers=25"
env CUDA_VISIBLE_DEVICES=2 SA_SPLIT=test python -m experiments.benchmark_with_steering --model qwen-2.5-14b-instruct --n 100 --examples 0 --tasks id_leverage --vector-variant sp --steering-mode add --vector-source id_leverage --coefficient 0.025 --layers 25 --out-dir experiments/results/qwen_steering --comment "vv=sp coef=0.025 layers=25"
env CUDA_VISIBLE_DEVICES=3 SA_SPLIT=test python -m experiments.benchmark_with_steering --model qwen-2.5-14b-instruct --n 100 --examples 0 --tasks id_leverage --vector-variant sp --steering-mode add --vector-source id_leverage --coefficient 0.05 --layers 25 --out-dir experiments/results/qwen_steering --comment "vv=plain coef=0.05 layers=25"

# env CUDA_VISIBLE_DEVICES=2 SA_SPLIT=test python -m experiments.benchmark_with_steering --model qwen-2.5-14b-instruct --n 100 --examples 0 --tasks stages --vector-variant plain --steering-mode add --vector-source stages --coefficient 0.025 --layers 25 --out-dir experiments/results/qwen_steering --comment "vv=plain coef=0.025 layers=25"
#env CUDA_VISIBLE_DEVICES=3 SA_SPLIT=test python -m experiments.benchmark_with_steering --model qwen-2.5-14b-instruct --n 100 --examples 0 --tasks stages --vector-variant sp --steering-mode add --vector-source stages --coefficient 0.025 --layers 25 --out-dir experiments/results/qwen_steering --comment "vv=sp coef=0.025 layers=25"
#env CUDA_VISIBLE_DEVICES=4 SA_SPLIT=test python -m experiments.benchmark_with_steering --model qwen-2.5-14b-instruct --n 100 --examples 0 --tasks output_control --vector-variant plain --steering-mode add --vector-source output_control --coefficient 0.025 --layers 25 --out-dir experiments/results/qwen_steering --comment "vv=plain coef=0.025 layers=25"
#env CUDA_VISIBLE_DEVICES=5 SA_SPLIT=test python -m experiments.benchmark_with_steering --model qwen-2.5-14b-instruct --n 100 --examples 0 --tasks output_control --vector-variant sp --steering-mode add --vector-source output_control --coefficient 0.025 --layers 25 --out-dir experiments/results/qwen_steering --comment "vv=sp coef=0.025 layers=25"
